name: Waxctl Deploy to AWS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (staging or production)'
        required: true
        default: 'staging'
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - run: |
          echo "deployment on ${{ github.event.inputs.environment }}"
          echo "dataflow deployed: https://raw.githubusercontent.com/bytewax/waxctl-sample-aws/${{ github.sha }}/dataflow.py"
          echo "requirements used: https://raw.githubusercontent.com/bytewax/waxctl-sample-aws/${{ github.sha }}/requirements.txt"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Install waxctl
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew tap bytewax/tap
        brew install waxctl

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - name: Waxctl Deploy
      run: |
        flow=$(waxctl aws ls | grep wikievents | awk '{print $1;}')
        if [ "$flow" = "wikievents" ];
        then
          waxctl aws delete --name wikievents --yes
          sleep 5
          waxctl aws rm --name "wikievents" --yes
        else
          waxctl aws deploy \
          https://raw.githubusercontent.com/bytewax/waxctl-sample-aws/${{ github.sha }}/dataflow.py \
          --requirements-file-name https://raw.githubusercontent.com/bytewax/waxctl-sample-aws/${{ github.sha }}/requirements.txt \
          --name wikievents
        fi;
        sleep 10
        waxctl aws ls --verbose
