name: Waxctl Deploy to AWS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (staging or production)'
        required: true
        default: 'staging'
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - run: |
          echo "deployment on ${{ github.event.inputs.environment }}"
          echo "dataflow deployed: https://raw.githubusercontent.com/bytewax/waxctl-sample-aws/${{ github.sha }}/dataflow.py"
          echo "requirements used: https://raw.githubusercontent.com/bytewax/waxctl-sample-aws/${{ github.sha }}/requirements.txt"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Install waxctl
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew tap bytewax/tap
        brew install waxctl

    - name: Waxctl Deploy
      run: |
        cat <<EOF >> $HOME/.waxctl/config.yaml
        collect_telemetry: true
        EOF
        flow=$(/home/linuxbrew/.linuxbrew/bin/waxctl aws ls | grep wikievents | awk '{print $1;}')
        if [ "$flow" = "wikievents" ];
        then
          /home/linuxbrew/.linuxbrew/bin/waxctl aws delete --name wikievents --yes --debug
          while ["$flow" = "wikievents"]
          do
            flow=$(/home/linuxbrew/.linuxbrew/bin/waxctl aws ls | grep wikievents | awk '{print $1;}')
            sleep 2
          done
        fi;
        /home/linuxbrew/.linuxbrew/bin/waxctl aws deploy \
        https://raw.githubusercontent.com/bytewax/waxctl-sample-aws/${{ github.sha }}/dataflow.py \
        --requirements-file-name https://raw.githubusercontent.com/bytewax/waxctl-sample-aws/${{ github.sha }}/requirements.txt \
        --name wikievents \
        --debug
        sleep 5
        waxctl aws ls --verbose
